# Site settings
title: Akhil Acharya
email: akhilcacharya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I build cool things with smart people.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akhilcacharya.me" # the base hostname & protocol for your site
github_username:  akhilcacharya

# Build settings
# markdown: kramdown
# highlighter: redcarpet
